[package]
name = "cafe-sys"
version = "0.1.0"
authors = ["29th-Day"]
edition = "2024"
license-file = "LICENSE"
keywords = ["wiiu", "homebrew"]
description = "Bindings for the Wii U system APIs"
repository = "https://github.com/rust-wiiu/cafe-sys"

[lib]
test = false
bench = false

[dependencies]
bitfields = "3.0.0"
bitflags = "2.13.0"
num_enum = { version = "0.7.6", default-features = false }
